"""Fusion #11 -- **Lazy Pre-Norm**: RMSNorm fused into a GEMM as a *prologue*.

Algorithm (Zhou et al., PyTorch blog 2026-07-10, section 2).  For an affine-free RMSNorm
the row scale commutes with the matmul::

    (A * rstd[:, None]) @ B  ==  (A @ B) * rstd[:, None]

so a GEMM CTA can accumulate ``acc += tile_A @ tile_B`` and ``sq += (tile_A*tile_A).sum(-1)``
in the SAME k-loop and apply ``rstd = rsqrt(sq/K + eps)`` as an **epilogue** scale.  The
cyclic dependency (rstd is needed before the k-loop, but only known after it) disappears.

GLM-5.2's RMSNorm *does* have an affine weight ``w`` [K].  The blog calls this a blocker;
at inference it is not one, because ``w`` is a *column* scale of A and B is a constant::

    ((A * rstd) * w) @ B  ==  (A @ (w[:, None] * B)) * rstd

``w`` is therefore folded into B's **rows** once, offline, outside every timed region --
a load-time weight transform, exactly like a quantization scale merge.  ``fold_weight_*``
below does it; ``glm52/bench/bench_f11_lazy_prenorm.py`` validates the folded result
against the unfolded ``reference.rmsnorm`` + matmul before it times anything.

ONE kernel source per consumer, a single ``tl.constexpr FUSE_NORM`` flag selecting the
behaviour:

* ``FUSE_NORM=False`` -- plain GEMM.  A is the **pre-normalized** ``x2`` and B is the raw
  weight.  The unfused chain therefore needs a separate RMSNorm kernel first
  (``glm52.kernels.add_rmsnorm.norm_only``, i.e. F3's tuned norm kernel).
* ``FUSE_NORM=True``  -- the SAME GEMM reads the **un-normalized** ``h1`` and B is the
  ``w``-folded weight; a per-row fp32 sum-of-squares rides along in the k-loop and the
  epilogue applies ``rstd``.  ``x2`` is never materialized.

Only the *mapping* (BLOCK_M/N/K, num_warps, num_stages, GROUP_M) differs between the two
sides, and each side is tuned independently over grids generated by the same rules.

Two consumers of ``post_attention_layernorm`` have K == hidden == 6144 and are covered:

  (a) ``moe_gateup_prenorm_kernel`` -- the routed-expert w13 grouped GEMM, structurally a
      copy of sglang 0.5.10's ``fused_moe_kernel`` (same sorted_token_ids / expert_ids /
      num_tokens_post_padded dispatch, same ``offs_token // top_k`` gather).  N = 2*I =
      4096, so a row's sum-of-squares is recomputed by ``cdiv(4096, BLOCK_N)`` n-tiles
      *and* by each of the ``top_k`` gathered copies of the token -> big redundancy.
  (b) ``router_gemm_kernel`` -- the dense router GEMM ``[T,6144] @ [6144,256]``.  N = 256
      means 1-4 n-tiles, so redundancy is ~1x: the near-ideal case for this fusion.

``SQ_MODE`` selects among four numerically equivalent ways to accumulate the sum of
squares.  On this MACA backend they are NOT equally fast, and which one wins depends on
``BLOCK_N`` -- see log/LOG-07-F11-lazy-prenorm.md section 5:

* ``0`` -- ``sq += tl.sum(af*af, axis=1)`` per k-step; the blog's pseudocode.
* ``1`` -- ``sqt += af*af`` into a [BLOCK_M, BLOCK_K] fp32 tile, one reduce after the
  loop: no per-step cross-lane reduction, but BLOCK_M*BLOCK_K extra fp32 registers.
* ``2`` -- ``sqd += tl.dot(a*a, ones[BLOCK_K, 16])``: the sum of squares runs on the
  **tensor core**, so ``a`` never leaves its dot-operand layout and no cross-lane
  reduction or layout conversion is emitted.  Costs ``16/BLOCK_N`` extra MMA flops, so it
  only pays off for wide tiles (it wins the w13 GEMM, loses the router GEMM).
  ``a*a`` rounds to bf16 before the MMA; measured cost is 2e-6 of extra relative error.
* ``3`` -- ``a`` re-loaded with a second ``tl.load`` and then mode 0.  Intended to test
  whether the dot-operand -> blocked layout conversion is the cost; Triton CSEs the two
  loads, so it compiles to exactly mode 0 and times identically.  Kept as evidence.

The mode is picked by a documented pre-study (recorded as ``sq_mode_study`` in the result
JSON) and then held FIXED so that the fused and unfused tuning grids have identical size.
"""

from __future__ import annotations

import torch
import triton
import triton.language as tl


# ======================================================================================
# offline weight folding  (load-time transform, never inside a timed region)
# ======================================================================================
def fold_weight_rowmajor(b: torch.Tensor, w: torch.Tensor) -> torch.Tensor:
    """B is [K, N] (contraction dim first): scale ROW k by w[k]."""
    return (b.float() * w.float()[:, None]).to(b.dtype)


def fold_weight_nk(bt: torch.Tensor, w: torch.Tensor) -> torch.Tensor:
    """B^T is [..., N, K] (nn.Linear / sglang w13 layout): scale COLUMN k by w[k]."""
    return (bt.float() * w.float()).to(bt.dtype)


# ======================================================================================
# (a) routed-expert w13 grouped GEMM, sglang `fused_moe_kernel` shape + lazy pre-norm
# ======================================================================================
@triton.jit
def moe_gateup_prenorm_kernel(
    a_ptr,  # [T, K] bf16 -- x2 (FUSE_NORM=False) or h1 (FUSE_NORM=True)
    b_ptr,  # [E, N, K] bf16 -- w13 (raw) or w13 folded with the rmsnorm weight
    c_ptr,  # [T*top_k, N] bf16
    rstd_ptr,  # [T] fp32 -- only read when USE_RSTD
    sorted_token_ids_ptr,
    expert_ids_ptr,
    num_tokens_post_padded_ptr,
    N,
    K,
    EM,
    num_valid_tokens,
    stride_am,
    stride_ak,
    stride_be,
    stride_bk,
    stride_bn,
    stride_cm,
    stride_cn,
    eps,
    BLOCK_SIZE_M: tl.constexpr,
    BLOCK_SIZE_N: tl.constexpr,
    BLOCK_SIZE_K: tl.constexpr,
    GROUP_SIZE_M: tl.constexpr,
    top_k: tl.constexpr,
    compute_type: tl.constexpr,
    even_Ks: tl.constexpr,
    FUSE_NORM: tl.constexpr,
    SQ_MODE: tl.constexpr,
    USE_RSTD: tl.constexpr,
):
    # ---- grouped pid swizzle (sglang) ------------------------------------------------
    pid = tl.program_id(axis=0)
    num_pid_m = tl.cdiv(EM, BLOCK_SIZE_M)
    num_pid_n = tl.cdiv(N, BLOCK_SIZE_N)
    num_pid_in_group = GROUP_SIZE_M * num_pid_n
    group_id = pid // num_pid_in_group
    first_pid_m = group_id * GROUP_SIZE_M
    group_size_m = min(num_pid_m - first_pid_m, GROUP_SIZE_M)
    pid_m = first_pid_m + ((pid % num_pid_in_group) % group_size_m)
    pid_n = (pid % num_pid_in_group) // group_size_m

    # ---- dispatch --------------------------------------------------------------------
    num_tokens_post_padded = tl.load(num_tokens_post_padded_ptr)
    if pid_m * BLOCK_SIZE_M >= num_tokens_post_padded:
        return

    offs_token_id = pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M).to(tl.int64)
    offs_token = tl.load(sorted_token_ids_ptr + offs_token_id).to(tl.int64)
    token_mask = offs_token < num_valid_tokens

    off_experts = tl.load(expert_ids_ptr + pid_m).to(tl.int64)

    offs_bn = (pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N).to(tl.int64)) % N
    offs_k = tl.arange(0, BLOCK_SIZE_K)

    # Padded dispatch slots carry the sentinel `num_valid_tokens`; the MACA pipeliner
    # emits speculative (unpredicated) prologue loads, so the sentinel row must not even
    # be *addressed*.  Clamping to row 0 keeps every address in range; `token_mask` still
    # discards the value.  (Same guard as glm52/kernels/moe_gateup.py.)
    safe_token = tl.where(token_mask, offs_token, 0)
    a_ptrs = a_ptr + (
        safe_token[:, None] // top_k * stride_am + offs_k[None, :] * stride_ak
    )
    b_ptrs = (
        b_ptr
        + off_experts * stride_be
        + (offs_k[:, None] * stride_bk + offs_bn[None, :] * stride_bn)
    )

    acc = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=tl.float32)
    if FUSE_NORM:
        if SQ_MODE == 1:
            sqt = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_K), dtype=tl.float32)
        elif SQ_MODE == 2:
            sqd = tl.zeros((BLOCK_SIZE_M, 16), dtype=tl.float32)
            sq_ones = tl.full((BLOCK_SIZE_K, 16), 1.0, dtype=a_ptr.dtype.element_ty)
        else:
            sq = tl.zeros((BLOCK_SIZE_M,), dtype=tl.float32)

    for k_start in range(0, K, BLOCK_SIZE_K):
        if even_Ks:
            a = tl.load(a_ptrs, mask=token_mask[:, None], other=0.0)
            b = tl.load(b_ptrs)
        else:
            a = tl.load(
                a_ptrs,
                mask=token_mask[:, None] & (offs_k[None, :] < K - k_start),
                other=0.0,
            )
            b = tl.load(b_ptrs, mask=offs_k[:, None] < K - k_start, other=0.0)

        acc += tl.dot(a, b)
        if FUSE_NORM:
            if SQ_MODE == 2:
                # sum of squares on the TENSOR CORE: (a*a) @ ones.  Keeps `a` in its
                # dot-operand layout, so no cross-lane reduction and no layout
                # conversion; costs 16/BLOCK_N extra MMA flops instead.
                sqd += tl.dot(a * a, sq_ones)
            elif SQ_MODE == 3:
                # A loaded a SECOND time, so the copy feeding the reduction gets a
                # plain blocked layout (the extra read is L2-resident).
                a2 = tl.load(a_ptrs, mask=token_mask[:, None], other=0.0).to(tl.float32)
                sq += tl.sum(a2 * a2, axis=1)
            else:
                af = a.to(tl.float32)
                if SQ_MODE == 1:
                    sqt += af * af
                else:
                    sq += tl.sum(af * af, axis=1)

        a_ptrs += BLOCK_SIZE_K * stride_ak
        b_ptrs += BLOCK_SIZE_K * stride_bk

    # ---- lazy epilogue: the whole normalization, deferred past the k-loop -------------
    if FUSE_NORM:
        if SQ_MODE == 1:
            sq = tl.sum(sqt, axis=1)
        elif SQ_MODE == 2:
            sq = tl.sum(sqd, axis=1) * 0.0625  # all 16 columns hold the same value
        rstd = 1.0 / tl.sqrt(sq / K + eps)
        acc = acc * rstd[:, None]
    elif USE_RSTD:
        # "half-fused" variant: rstd came from a tiny separate reduction kernel, so the
        # k-loop is byte-for-byte the unfused one and only the epilogue scale is added.
        rstd = tl.load(rstd_ptr + safe_token // top_k, mask=token_mask, other=1.0)
        acc = acc * rstd[:, None]

    out = acc.to(compute_type)

    offs_cn = pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)
    c_ptrs = c_ptr + stride_cm * safe_token[:, None] + stride_cn * offs_cn[None, :]
    c_mask = token_mask[:, None] & (offs_cn[None, :] < N)
    tl.store(c_ptrs, out, mask=c_mask)


# ======================================================================================
# (b) dense router GEMM  [M, K] @ [K, N] -> fp32 logits, with lazy pre-norm
# ======================================================================================
@triton.jit
def router_gemm_kernel(
    a_ptr,  # [M, K] bf16 -- x2 (FUSE_NORM=False) or h1 (FUSE_NORM=True)
    b_ptr,  # [K, N] bf16 -- gate weight^T (raw) or folded with the rmsnorm weight
    c_ptr,  # [M, N] fp32 -- router logits (moe_router_dtype == float32)
    rstd_ptr,  # [M] fp32 -- only read when USE_RSTD
    M,
    N,
    K,
    stride_am,
    stride_ak,
    stride_bk,
    stride_bn,
    stride_cm,
    stride_cn,
    eps,
    BLOCK_SIZE_M: tl.constexpr,
    BLOCK_SIZE_N: tl.constexpr,
    BLOCK_SIZE_K: tl.constexpr,
    GROUP_SIZE_M: tl.constexpr,
    even_Ks: tl.constexpr,
    FUSE_NORM: tl.constexpr,
    SQ_MODE: tl.constexpr,
    USE_RSTD: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    num_pid_m = tl.cdiv(M, BLOCK_SIZE_M)
    num_pid_n = tl.cdiv(N, BLOCK_SIZE_N)
    num_pid_in_group = GROUP_SIZE_M * num_pid_n
    group_id = pid // num_pid_in_group
    first_pid_m = group_id * GROUP_SIZE_M
    group_size_m = min(num_pid_m - first_pid_m, GROUP_SIZE_M)
    pid_m = first_pid_m + ((pid % num_pid_in_group) % group_size_m)
    pid_n = (pid % num_pid_in_group) // group_size_m

    offs_m = pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)
    m_mask = offs_m < M
    safe_m = tl.where(m_mask, offs_m, 0)  # never address past the end of A
    offs_bn = (pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)) % N
    offs_k = tl.arange(0, BLOCK_SIZE_K)

    a_ptrs = a_ptr + (safe_m[:, None] * stride_am + offs_k[None, :] * stride_ak)
    b_ptrs = b_ptr + (offs_k[:, None] * stride_bk + offs_bn[None, :] * stride_bn)

    acc = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=tl.float32)
    if FUSE_NORM:
        if SQ_MODE == 1:
            sqt = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_K), dtype=tl.float32)
        elif SQ_MODE == 2:
            sqd = tl.zeros((BLOCK_SIZE_M, 16), dtype=tl.float32)
            sq_ones = tl.full((BLOCK_SIZE_K, 16), 1.0, dtype=a_ptr.dtype.element_ty)
        else:
            sq = tl.zeros((BLOCK_SIZE_M,), dtype=tl.float32)

    for k_start in range(0, K, BLOCK_SIZE_K):
        if even_Ks:
            a = tl.load(a_ptrs, mask=m_mask[:, None], other=0.0)
            b = tl.load(b_ptrs)
        else:
            a = tl.load(
                a_ptrs,
                mask=m_mask[:, None] & (offs_k[None, :] < K - k_start),
                other=0.0,
            )
            b = tl.load(b_ptrs, mask=offs_k[:, None] < K - k_start, other=0.0)

        acc += tl.dot(a, b)
        if FUSE_NORM:
            if SQ_MODE == 2:
                # sum of squares on the TENSOR CORE: (a*a) @ ones.  Keeps `a` in its
                # dot-operand layout, so no cross-lane reduction and no layout
                # conversion; costs 16/BLOCK_N extra MMA flops instead.
                sqd += tl.dot(a * a, sq_ones)
            elif SQ_MODE == 3:
                # A loaded a SECOND time, so the copy feeding the reduction gets a
                # plain blocked layout (the extra read is L2-resident).
                a2 = tl.load(a_ptrs, mask=m_mask[:, None], other=0.0).to(tl.float32)
                sq += tl.sum(a2 * a2, axis=1)
            else:
                af = a.to(tl.float32)
                if SQ_MODE == 1:
                    sqt += af * af
                else:
                    sq += tl.sum(af * af, axis=1)

        a_ptrs += BLOCK_SIZE_K * stride_ak
        b_ptrs += BLOCK_SIZE_K * stride_bk

    if FUSE_NORM:
        if SQ_MODE == 1:
            sq = tl.sum(sqt, axis=1)
        elif SQ_MODE == 2:
            sq = tl.sum(sqd, axis=1) * 0.0625  # all 16 columns hold the same value
        rstd = 1.0 / tl.sqrt(sq / K + eps)
        acc = acc * rstd[:, None]
    elif USE_RSTD:
        rstd = tl.load(rstd_ptr + safe_m, mask=m_mask, other=1.0)
        acc = acc * rstd[:, None]

    offs_cn = pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)
    c_ptrs = c_ptr + stride_cm * safe_m[:, None] + stride_cn * offs_cn[None, :]
    tl.store(c_ptrs, acc, mask=m_mask[:, None] & (offs_cn[None, :] < N))


# ======================================================================================
# "half-fused" helper: rstd-only reduction  ([T, K] bf16 -> [T] fp32)
#
# This is the third point on the design axis and it exists because of what the
# measurements below show.  Traffic per activation pass (`act = T*H*2`):
#
#   unfused      norm kernel reads act, writes act ; GEMM reads act        -> 3 act
#   rstd-only    rstd kernel reads act             ; GEMM reads act        -> 2 act
#   lazy prenorm                                     GEMM reads act        -> 1 act
#
# so it captures 2/3 of the fusion's byte saving while leaving the GEMM's k-loop
# byte-for-byte identical to the unfused one -- no fp32 conversion of the A tile, no
# per-step reduction, no extra live registers in the mainloop.
# ======================================================================================
@triton.jit
def rstd_kernel(
    X,  # [T, N] bf16
    RSTD,  # [T]    fp32
    stride_x,
    T,
    N,
    eps,
    ROWS: tl.constexpr,
    BLOCK_N: tl.constexpr,
    N_TILES: tl.constexpr,
):
    pid = tl.program_id(0)
    rows = pid * ROWS + tl.arange(0, ROWS)
    rmask = rows < T
    acc = tl.zeros([ROWS], dtype=tl.float32)
    for t in tl.static_range(N_TILES):
        cols = t * BLOCK_N + tl.arange(0, BLOCK_N)
        m = rmask[:, None] & (cols[None, :] < N)
        x = tl.load(X + rows[:, None] * stride_x + cols[None, :], mask=m, other=0.0)
        xf = x.to(tl.float32)
        acc += tl.sum(xf * xf, axis=1)
    tl.store(RSTD + rows, 1.0 / tl.sqrt(acc / N + eps), mask=rmask)


def launch_rstd(x, rstd, cfg, eps: float = 1e-5):
    T, N = x.shape
    bn = cfg["BLOCK_N"]
    grid = (triton.cdiv(T, cfg["ROWS"]),)
    return rstd_kernel[grid](
        x,
        rstd,
        x.stride(0),
        T,
        N,
        eps,
        ROWS=cfg["ROWS"],
        BLOCK_N=bn,
        N_TILES=triton.cdiv(N, bn),
        num_warps=cfg["num_warps"],
        num_stages=cfg["num_stages"],
    )


# ======================================================================================
# SMEM pre-filter and thin launchers
# ======================================================================================
def smem_bytes(cfg: dict) -> int:
    """Triton pipeline SMEM footprint: num_stages * 2 B/elt * BK * (BM + BN).

    Identical for FUSE_NORM on and off -- the fusion stages no extra tile, which is
    already a structural difference from F6 (where the second B tile made the unfused
    winner uncompilable)."""
    return cfg["num_stages"] * 2 * cfg["BLOCK_K"] * (cfg["BLOCK_M"] + cfg["BLOCK_N"])


def launch_moe_gateup(
    a,
    b,
    c,
    sorted_token_ids,
    expert_ids,
    num_tokens_post_padded,
    num_valid_tokens,
    top_k,
    cfg,
    fuse_norm: bool,
    eps: float = 1e-5,
    sq_mode: int = 0,
    rstd=None,
):
    """`a`: [T,K] bf16.  `b`: [E,N,K] bf16.  `c`: [T*top_k, N] bf16."""
    N = c.shape[1]
    K = a.shape[1]
    EM = sorted_token_ids.shape[0]
    grid = (triton.cdiv(EM, cfg["BLOCK_M"]) * triton.cdiv(N, cfg["BLOCK_N"]),)
    return moe_gateup_prenorm_kernel[grid](
        a,
        b,
        c,
        rstd if rstd is not None else c,
        sorted_token_ids,
        expert_ids,
        num_tokens_post_padded,
        N,
        K,
        EM,
        num_valid_tokens,
        a.stride(0),
        a.stride(1),
        b.stride(0),
        b.stride(2),
        b.stride(1),
        c.stride(0),
        c.stride(1),
        eps,
        BLOCK_SIZE_M=cfg["BLOCK_M"],
        BLOCK_SIZE_N=cfg["BLOCK_N"],
        BLOCK_SIZE_K=cfg["BLOCK_K"],
        GROUP_SIZE_M=cfg["GROUP_M"],
        top_k=top_k,
        compute_type=tl.bfloat16,
        even_Ks=(K % cfg["BLOCK_K"] == 0),
        FUSE_NORM=fuse_norm,
        SQ_MODE=sq_mode,
        USE_RSTD=rstd is not None,
        num_warps=cfg["num_warps"],
        num_stages=cfg["num_stages"],
    )


def launch_router(
    a, b, c, cfg, fuse_norm: bool, eps: float = 1e-5, sq_mode: int = 0, rstd=None
):
    """`a`: [M,K] bf16.  `b`: [K,N] bf16.  `c`: [M,N] fp32."""
    M, K = a.shape
    N = c.shape[1]
    grid = (triton.cdiv(M, cfg["BLOCK_M"]) * triton.cdiv(N, cfg["BLOCK_N"]),)
    return router_gemm_kernel[grid](
        a,
        b,
        c,
        rstd if rstd is not None else c,
        M,
        N,
        K,
        a.stride(0),
        a.stride(1),
        b.stride(0),
        b.stride(1),
        c.stride(0),
        c.stride(1),
        eps,
        BLOCK_SIZE_M=cfg["BLOCK_M"],
        BLOCK_SIZE_N=cfg["BLOCK_N"],
        BLOCK_SIZE_K=cfg["BLOCK_K"],
        GROUP_SIZE_M=cfg["GROUP_M"],
        even_Ks=(K % cfg["BLOCK_K"] == 0),
        FUSE_NORM=fuse_norm,
        SQ_MODE=sq_mode,
        USE_RSTD=rstd is not None,
        num_warps=cfg["num_warps"],
        num_stages=cfg["num_stages"],
    )
